export const PRODUCTS = [
  { id: 1, name: 'Pork Siomai', category: 'siomai', price: 25.00, description: 'Juicy pork siomai with authentic Filipino flavors', image: 'https://media.istockphoto.com/id/2182583656/photo/chinese-steamed-dumpling-or-shumai-in-japanese-language-meatball-dumpling-with-wanton-skin.jpg?s=612x612&w=0&k=20&c=0K7_ee0dwfAZhcZZajZRSv8uTifXZhG6LVmlKnSe-0U=' },
  { id: 2, name: 'Chicken Siomai', category: 'siomai', price: 25.00, description: 'Tender chicken siomai with fresh ingredients', image: 'https://media.istockphoto.com/id/1336438874/photo/delicious-dim-sum-home-made-chinese-dumplings-served-on-plate.jpg?s=612x612&w=0&k=20&c=11KB0bXoZeMrlzaHN2q9aZq8kqtdvp-d4Oggc2TF8M4=' },
  { id: 3, name: 'Beef Siomai', category: 'siomai', price: 25.00, description: 'Premium beef siomai with a rich savory taste', image: 'https://media.istockphoto.com/id/2189370578/photo/delicious-shumai-shumay-siomay-chicken-in-bowl-snack-menu.jpg?s=612x612&w=0&k=20&c=hD4kuZsiGIjgyUPq-seqv229pFE43CnS0Do3EH_2E_Y=' },
  { id: 4, name: 'Tuna Siomai', category: 'siomai', price: 25.00, description: 'Fresh tuna siomai with an ocean-fresh flavor', image: 'https://media.istockphoto.com/id/1084916088/photo/close-up-cooking-homemade-shumai.jpg?s=612x612&w=0&k=20&c=M1RyWV62MACQffBC40UzZ_h-BsXOj4bkaMBrxnbMTzc=' },
  { id: 5, name: 'Shark\'s Fin Siomai', category: 'siomai', price: 25.00, description: 'Premium shark\'s fin siomai with a delicate texture', image: 'https://media.istockphoto.com/id/1330456626/photo/steamed-shark-fin-dumplings-served-with-chili-garlic-oil-and-calamansi.jpg?s=612x612&w=0&k=20&c=9Zi1JmbwvYtIlZJqZb6tHOVC21rS-IbwZXS-IeflE30=' },
  { id: 6, name: 'Japanese Siomai', category: 'siomai', price: 25.00, description: 'Japanese-style siomai with nori wrapping', image: 'https://media.istockphoto.com/id/1221287744/photo/ground-pork-with-crab-stick-wrapped-in-nori.jpg?s=612x612&w=0&k=20&c=Rniq7tdyCqVZHpwngsbzOk1dG1u8pTEeUDE8arsfOUY=' },
  { id: 7, name: 'Asado Siopao', category: 'siopao', price: 45.00, description: 'Classic asado siopao with sweet-savory pork filling', image: 'https://media.istockphoto.com/id/1163708923/photo/hong-kong-style-chicken-char-siew-in-classic-polo-bun-polo-bun-or-is-a-kind-of-crunchy-and.jpg?s=612x612&w=0&k=20&c=R9DC49-UsxYUPlImX6O47LQyafOu1Cp5rNxp3XifFNI=' },
  { id: 8, name: 'Bola-Bola Siopao', category: 'siopao', price: 45.00, description: 'Hearty bola-bola siopao with meatball filling', image: 'https://media.istockphoto.com/id/1184080523/photo/wanton-noodle-soup-and-siopao.jpg?s=612x612&w=0&k=20&c=oRJanjrTxICQfuzm9bXVPYkw9nKh74tcwjH1cVzXzN8=' },
  { id: 9, name: 'Choco Siopao', category: 'siopao', price: 45.00, description: 'Sweet chocolate-filled siopao for dessert lovers', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxSCl2zlIK85vMZ6nRYuWpqde6JnIxBUTe-w&s' },
  { id: 10, name: 'Ube Siopao', category: 'siopao', price: 45.00, description: 'Filipino ube-flavored siopao with purple yam', image: 'https://media.istockphoto.com/id/2161276374/photo/vivid-steamed-purple-ube-sweet-potato-dumplings.jpg?s=612x612&w=0&k=20&c=Mb2rl1JZPvG0d5v-_gSC7Mx50DNggFJiTEcoTayqB1Q=' },
  { id: 11, name: 'Red Bean Siopao', category: 'siopao', price: 45.00, description: 'Traditional red bean paste siopao with sweet flavor', image: 'https://media.istockphoto.com/id/1172915611/photo/asian-steamed-bun-with-adzuki-red-bean-paste-filling-or-bakpao.jpg?s=612x612&w=0&k=20&c=hImY86ZyoR8y2FC17yLpkCA5amxrZDxCeuVokJnY5w0=' },
  { id: 12, name: 'Custard Siopao', category: 'siopao', price: 45.00, description: 'Creamy custard-filled siopao with rich texture', image: 'https://media.istockphoto.com/id/957584318/photo/chinese-steamed-bun-and-orange-sweet-creamy-lava-on-chinese-pattern-dish.jpg?s=612x612&w=0&k=20&c=5CJuHZdTLVIlN5gq_jmer--RWri-TDliTtQoIvAc97M=' }
];
